channels:
  - simpleitk
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.16
  - annotated-types=0.6.0
  - app-model=0.3.0
  - appdirs=1.4.4
  - asciitree=0.3.3
  - asttokens=3.0.0
  - attrs=24.3.0
  - babel=2.11.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.14
  - cachey=0.2.1
  - certifi=2024.12.14
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cytoolz=0.12.2
  - dask-core=2024.8.2
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.1.1
  - docstring_parser=0.16
  - docutils=0.18.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fasteners=0.16.3
  - flexcache=0.3
  - flexparser=0.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - freetype-py=2.2.0
  - fsspec=2024.6.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - heapdict=1.0.1
  - hsluv=5.0.3
  - icu=73.1
  - idna=3.7
  - imageio=2.36.1
  - imagesize=1.4.1
  - importlib-metadata=8.5.0
  - in-n-out=0.2.1
  - ipykernel=6.29.5
  - ipython=8.31.0
  - jedi=0.19.2
  - jinja2=3.1.4
  - jpeg=9e
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy_loader=0.4
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.11.1
  - libdeflate=1.8
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.4.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - libzlib=1.2.13
  - llvmlite=0.43.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - magicgui=0.9.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mdurl=0.1.0
  - msgpack-python=1.0.3
  - mysql=8.4.0
  - napari=0.5.5
  - napari-base=0.5.5
  - napari-console=0.1.3
  - napari-plugin-engine=0.2.0
  - napari-plugin-manager=0.1.3
  - napari-svg=0.2.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - npe2=0.7.7
  - numba=0.60.0
  - numcodecs=0.13.1
  - numexpr=2.10.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - numpydoc=1.7.0
  - openjpeg=2.4.0
  - openldap=2.6.4
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - partd=1.4.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pint=0.24.4
  - pip=24.2
  - platformdirs=4.3.6
  - ply=3.11
  - pooch=1.8.2
  - prompt-toolkit=3.0.48
  - psutil=6.1.1
  - psygnal=0.11.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyconify=0.2
  - pydantic=2.10.3
  - pydantic-compat=0.1.2
  - pydantic-core=2.27.1
  - pydicom=3.0.1
  - pygments=2.18.0
  - pyopengl=3.1.1a1
  - pyparsing=3.2.0
  - pyproject_hooks=1.0.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-build=0.10.0
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.0.1
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.1
  - pywavelets=1.7.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.2
  - qtconsole-base=5.6.1
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rich=13.9.4
  - rpds-py=0.10.6
  - scikit-image=0.25.0
  - scipy=1.14.1
  - setuptools=75.1.0
  - shellingham=1.5.0
  - simpleitk=2.2.1
  - sip=6.7.12
  - six=1.17.0
  - snowballstemmer=2.2.0
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlite=3.45.3
  - stack_data=0.6.3
  - superqt=0.6.7
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tifffile=2024.12.12
  - tk=8.6.14
  - tomli=2.0.1
  - tomli-w=1.0.0
  - toolz=0.12.0
  - tornado=6.4.2
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typer=0.9.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - vispy=0.14.3
  - wcwidth=0.2.13
  - wheel=0.44.0
  - wrapt=1.14.1
  - xz=5.4.6
  - yaml=0.2.5
  - zarr=2.18.3
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
